config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "create_fast" ,to: "users#create_fast"
  get "destroy_all" ,to: "users#destroy_all"
  get "main" ,to: "users#main"
  post "main" ,to: "users#login"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  def check_session(session_data)


    if(session_data != self.user_id)
      errors.add(:user_id,"You cann't create other people's post.")
      return false
    end
    return true
  end

  def addErrorUpdate
    errors.add(:user_id,"You cant edit other people's user_id")
    return false
  end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :posts
	has_secure_password

	validate :check_email, on: [:create ]
	validate :login, on: [:login]
	validate :edit_user, on: [:update]

	def edit_user
		@user = User.find_by(email:self.email)
		if(!@user || self.id == @user.id)
			return true
		else
			errors.add(:email,"The email already exists")
			return false
		end

	end
	def check_email
		@user = User.find_by(email:self.email)
		if(@user )
			errors.add(:email,"The email already exists")
		end

	end

	def login


		@user = User.find_by(email:self.email)

		if (!@user)
			errors.add(:email , "Your email isn't available in database")
			return false
		end


		if (@user.authenticate(self.password))
			return self.id = @user.id
		else
			errors.add(:password, "Invalid password")
			return false
		end





	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :logged_in,except: %i[]
  # GET /posts or /posts.json
  def index
  @posts = User.find(get_session_data).posts
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    check = @post.check_session(get_session_data)
    respond_to do |format|
      if (check && @post.save)

        format.html { redirect_to user_path get_session_data, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    check = true

    if (get_session_data.to_s != params[:post][:user_id])
      check = @post.addErrorUpdate
    end
    # puts "---------------------------------get_session_data = #{get_session_data}"
    # puts "---------------------------------params[:post][:user_id] = #{params[:post][:user_id]}"
    # puts "---------------------------------check = #{check}"
    respond_to do |format|
      if check && @post.update(post_params)
        format.html { redirect_to user_path get_session_data, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to user_path get_session_data, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:message, :user_id)
    end

    def get_session_data
      return session[:user_id]
    end

    def logged_in
      if get_session_data != nil
        return true
      else
        redirect_to main_path , notice: "Please login"
      end
    end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :logged_in, except: %i[index main login new create ]
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    if logged_in
    else
      return
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.posts.each do |p|
      p.destroy
    end
    @user.destroy
    # respond_to do |format|
    #   format.html { redirect_to users_url, notice: "User was successfully destroyed." }
    #   format.json { head :no_content }
    # end
  end

  def create_fast
    name = params[:name]
    email = params[:email]
    @user = User.create(name:name,email:email)

  end

  def destroy_all
    Post.all.each do |p|
      p.destroy
    end
    User.destroy_all
    redirect_to users_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :name, :birthdate ,:postal_code ,:address ,:password)
    end

    def logged_in
      if(session[:user_id] == @user.id)
        return true
      else
        redirect_to main_path , notice: "Please login"
      end
    end


    public
      def main
        session[:user_id] = nil
        @user = User.new()
      end



      def login
        @user = User.new(user_params)

       respond_to do |format|
            if @user.login
              session[:user_id] = @user.id
              format.html { redirect_to user_path(@user.id) }

            else
              session[:user_id] = nil
              format.html { render :main, status: :unprocessable_entity }
            end
        end
      end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Class4</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= "SESSION[:USER_ID] = #{session[:user_id]} "%>
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', user_path(session[:user_id]) %>

app/views/posts/index.html.erb
<%= "SESSION[:USER_ID] = #{session[:user_id]}" %>
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.message %></td>
        <td><%= post.user_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @post.message %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :postal_code %>
    <%= form.text_field :postal_code %>
  </div>
      <div class="field">
    <%= form.label :password%>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :birthdate %>
    <%= form.date_select :birthdate %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_formMain.html.erb
<%= form_with(model: user ,url: "/main") do |form| %>
 <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit value="submit"%>
  </div>
<% end %>

app/views/users/_postUser.html.erb
<p id="notice"><%= notice %></p>

<br> <br> <br>
<h1>Posts</h1>
<table >
  <thead >
    <tr >
      <th >Message</th>
      <th>time</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody >
    <% @user.posts.each do |post| %>
      <tr >
        <td ><%= post.message %></td>
        <td><%= post.created_at%></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/users/create_fast.html.erb
<p id="notice"><%= notice %></p>


<h1>Create Successfully</h1>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @user.birthdate %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/create_users.html.erb
<h1>Create User Again!!!!</h1>
<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>
<p>
  <b>Address:</b>
  <%= @user.address %>
</p>
<p>
  <b>Postal Code:</b>
  <%= @user.postal_code %>
</p>

<%= link_to 'index', users_url %> 

app/views/users/destroy.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @user.birthdate %>
</p>

<%= link_to 'index', users_path%>
<%= link_to 'create again', "/create_fast?name=#{@user.name}&email=#{@user.email}"%>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Birthdate</th>
      <th>Address</th>
      <th>Postal_code</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= user.birthdate %></td>
        <td><%= user.address %></td>
        <td><%= user.postal_code %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

<%= link_to 'destroy_all', destroy_all_path %>

app/views/users/main.html.erb
<p id="notice"><%= notice %></p>
<h1>Login</h1>

<%= render "formMain" ,user:@user %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @user.birthdate %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Postal_code:</strong>
  <%= @user.postal_code %>
</p>

<p>
  <strong>password:</strong>
  <%= @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

<%= render "postUser"%>